Rework WorldGen drop
way2muchnoise/JustEnoughResources pull request #324
Opened 2022-01-28 19:41 UTC by AlasDiablo

Hi, i'm currently working on a mod who add compatibility with Just Enough Resources and i have encountered some problem.

In this pr i have fix some issues and make some proposition of amelioration on drop display.

Have a nice day, and i will hope this can help you !
Sorry for my bad english.

Change with vanila ore:
![Iron Ore](https://user-images.githubusercontent.com/25723276/151610617-7d053470-74db-4b07-89ff-93b881aede63.jpg)

Change and fix with compatibility by mod creator ore:
![Certus Quartz](https://user-images.githubusercontent.com/25723276/151610860-9b9f7ac7-d8cc-466f-9aff-72ff54dd7056.jpg)

2022-02-12 12:02 UTC, Seniorendi commented
This is really neat

2022-02-14 11:03 UTC, way2muchnoise requested changes
Looks good to me with just the small change mentioned for generalisation.

2022-02-14 11:03 UTC, way2muchnoise commented on src/api/java/jeresources/api/drop/LootDrop.java
> +    public boolean isAffectedByFortune() {
Can we also add a general function for this, seems like a useful tool to me.
`public boolean isAffectedBy(Conditional)`

2022-02-15 18:34 UTC, way2muchnoise requested changes
One more change, could you bump the revision number in the following file https://github.com/way2muchnoise/JustEnoughResources/blob/master/gradle.properties#L5

2022-02-15 21:07 UTC, way2muchnoise approved these changes

2022-02-15 21:08 UTC, merged

2022-02-15 21:08 UTC, way2muchnoise commented
Thanks for the PR, new build with this new UI will be up on CF soon :)

2022-02-15 21:50 UTC, Seniorendi commented
Nice!