1.18.2 branch
way2muchnoise/JustEnoughResources pull request #387
Opened 2023-03-11 14:49 UTC by Christofmeg

Created branch from ([#346](https://github.com/way2muchnoise/JustEnoughResources/tree/95dc8c5afcd9828d14c3c2a62b6abca243e167b3))
Added spawn egg slot to 1.18.2
Changed "Experience Dropped" to "Experience". Ender dragon exp was overlapping with spawn egg slot.
Updated pack_format to match 1.18.2
Updated version to 14.2.1
Wandering Trades
Deepslate Ores
Merged changes from:
- ([https://github.com/way2muchnoise/JustEnoughResources/issues/328](https://github.com/way2muchnoise/JustEnoughResources/issues/328))
- ([https://github.com/way2muchnoise/JustEnoughResources/pull/368](https://github.com/way2muchnoise/JustEnoughResources/pull/368))
- ([https://github.com/way2muchnoise/JustEnoughResources/pull/367](https://github.com/way2muchnoise/JustEnoughResources/pull/367))
- ([https://github.com/way2muchnoise/JustEnoughResources/pull/375](https://github.com/way2muchnoise/JustEnoughResources/pull/375))
- ([https://github.com/way2muchnoise/JustEnoughResources/pull/378](https://github.com/way2muchnoise/JustEnoughResources/pull/378))
- ([https://github.com/way2muchnoise/JustEnoughResources/pull/384](https://github.com/way2muchnoise/JustEnoughResources/pull/384))
-  [https://github.com/way2muchnoise/JustEnoughResources/issues/352](https://github.com/way2muchnoise/JustEnoughResources/issues/352)
- [https://github.com/way2muchnoise/JustEnoughResources/pull/366](https://github.com/way2muchnoise/JustEnoughResources/pull/366)
- Optimizations based upon [https://github.com/way2muchnoise/JustEnoughResources/commit/f29c18a9183aa566a327da130f62b91f63b742d9](https://github.com/way2muchnoise/JustEnoughResources/commit/f29c18a9183aa566a327da130f62b91f63b742d9)

2023-03-12 16:20 UTC, way2muchnoise requested changes
I create the actual 1.18.2 target branch, can you please update where needed?

2023-03-16 21:43 UTC, way2muchnoise requested changes
one small change remains and we can pull this in

2023-03-16 21:43 UTC, way2muchnoise commented on gradle.properties
> +version_revis=2.1
This should just be 2 and not 2.1

2023-03-18 17:06 UTC, way2muchnoise commented
Looks like the build is failing on Travis, does it build locally?

2023-03-19 14:08 UTC, merged

2023-03-19 14:10 UTC, way2muchnoise commented
Thanks for the PR

2023-03-19 21:56 UTC, Christofmeg commented
@way2muchnoise Will you be uploading the new version to CurseForge / Modrinth in the near future?

2023-03-20 12:28 UTC, way2muchnoise commented
Already on CF https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/4445746

Need to look into uploading to Modrinth, had a similar request on [BetterAdvancements#122](https://github.com/way2muchnoise/BetterAdvancements/issues/122).